version: "3.9"

services:
  front:
    container_name: front
    build: ./front/
    ports:
      - "80:80"
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - "8080:5000"
  db:
    container_name: db
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
      
volumes:
  postgres: